version: '3'

services:

  example-app:
    image: drill4j/scala-spring-sample:${SCALA_SPRING_APP_BUILD}
    ports:
      - ${SCALA_SPRING_APP_PORT}:8080
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=${ADMIN_ADDRESS},agentId=${AGENT_ID},buildVersion=${SCALA_SPRING_APP_BUILD},logLevel=${LOG_LEVEL}"
    volumes:
      - agent-files:/data

  agent-files:
    image: drill4j/java-agent:0.7.0-28
    volumes:
      - agent-files:/java-agent

volumes:
  agent-files: